spring.application.name=ifspace

# Configuração do Banco de Dados
spring.datasource.url=jdbc:postgresql://localhost:5432/sistema_salas
spring.datasource.username=seu_usuario
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuração do JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuração de Segurança (JWT)
app.jwt.secret=3xP@nJf37w1N@0z_T^A&gh!km$qR7q@YbVZk
app.jwt.expiration=86400000 

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

